# Generated by Django 4.1.7 on 2023-10-09 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='modules_for_students', to='backend.student'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, related_name='modules_for_teachers', to='backend.teacher'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='backend.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='backend.teacher'),
        ),
    ]
